apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyprus-signs-bot
spec:
  template:
    spec:
      containers:
        - name: bot
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
