#!/usr/bin/env python3
"""Full Cyprus road-sign catalog (13 categories, per driving.cy inventory).
Generates data/signs_full.json. Images are downloaded separately by fetch_images.py."""
import json
import os
import re
from urllib.parse import unquote

BASE = "https://driving.cy/signs/Signs/"
OUT = os.path.join(os.path.dirname(__file__), "..", "data")

CATEGORIES = {
    "warning":     {"ru": "Предупреждающие знаки", "en": "Warning signs"},
    "additional_markings": {"ru": "Дополнительная маркировка", "en": "Additional markings"},
    "prohibitory": {"ru": "Запрещающие и ограничивающие", "en": "Prohibitory or restriction signs"},
    "regulatory":  {"ru": "Регулирующие знаки", "en": "Regulatory signs"},
    "no_parking":  {"ru": "Знаки запрета парковки", "en": "No parking signs"},
    "mandatory":   {"ru": "Предписывающие знаки", "en": "Mandatory signs"},
    "info":        {"ru": "Информационные знаки", "en": "Information signs"},
    "additional":  {"ru": "Таблички-дополнения", "en": "Additional signs"},
    "other":       {"ru": "Прочие официальные знаки", "en": "Other official signs"},
    "north":       {"ru": "Северный Кипр / буферная зона", "en": "Northern Cyprus"},
    "warden":      {"ru": "Сигналы регулировщика", "en": "Signals by authorised persons"},
    "marking":     {"ru": "Дорожная разметка", "en": "Road markings"},
    "roundabout":  {"ru": "Круговые развязки", "en": "Roundabouts"},
}

# (category, name_en, name_ru, image filename on driving.cy)
S = [
 # ------------------------- WARNING (59) -------------------------
 ("warning","Traffic signals ahead","Впереди светофор","UK_traffic_sign_543.svg"),
 ("warning","Crossroads with priority to the right","Перекрёсток с приоритетом справа","Cyprus_warning_road_sign_crossroads.svg"),
 ("warning","T-junction","Т-образный перекрёсток","UK_traffic_sign_505.1_(left).svg"),
 ("warning","Junctions with secondary roads","Примыкание второстепенных дорог","UK_traffic_sign_506.1_(variant_1,_right).svg"),
 ("warning","Staggered junction with secondary roads","Смещённое примыкание второстепенных дорог","UK_traffic_sign_507.1_(variant_1,_right).svg"),
 ("warning","Traffic merges from the left","Слияние потока слева","UK_traffic_sign_508.1.svg"),
 ("warning","Traffic merges onto the main carriageway","Слияние с основной проезжей частью","UK_traffic_sign_509.1.svg"),
 ("warning","Roundabout (warning)","Впереди круговое движение","UK_traffic_sign_510.svg"),
 ("warning","Bend to right (left if reversed)","Поворот направо (налево — зеркально)","UK_traffic_sign_512_(right).svg"),
 ("warning","Double bend first to the left (right if reversed)","Двойной поворот, первый налево","UK_traffic_sign_513_(left).svg"),
 ("warning","Junction on a bend outside (may be reversed)","Примыкание на внешней стороне поворота","UK_traffic_sign_512.1_(right).svg"),
 ("warning","Junction on a bend inside (may be reversed)","Примыкание на внутренней стороне поворота","UK_traffic_sign_512.2_(right).svg"),
 ("warning","Road narrows on both sides","Сужение дороги с обеих сторон","UK_traffic_sign_516.svg"),
 ("warning","Road narrows on the right (left if reversed)","Сужение дороги справа","UK_traffic_sign_517_(right).svg"),
 ("warning","End of dual carriageway","Конец дороги с разделёнными проезжими частями","UK_traffic_sign_520.svg"),
 ("warning","Two-way traffic","Двустороннее движение","UK_traffic_sign_521.svg"),
 ("warning","Two-way traffic on route crossing ahead","Пересечение с двусторонним движением","UK_traffic_sign_522.svg"),
 ("warning","Steep descent","Крутой спуск","UK_traffic_sign_523.1.svg"),
 ("warning","Steep ascent","Крутой подъём","UK_traffic_sign_524.1.svg"),
 ("warning","Opening or swing bridge","Разводной мост","UK_traffic_sign_529.svg"),
 ("warning","Riverbank or quayside","Берег реки или набережная","UK_traffic_sign_555.svg"),
 ("warning","Water course alongside road","Водоём вдоль дороги","UK_traffic_sign_555.1.svg"),
 ("warning","Soft verges left","Мягкая обочина слева","UK_traffic_sign_556.1.svg"),
 ("warning","Soft verges right","Мягкая обочина справа","Cyprus_warning_road_sign_friable_street.svg"),
 ("warning","Tunnel","Тоннель","UK_traffic_sign_529.1.svg"),
 ("warning","Hump bridge","Горбатый мост","UK_traffic_sign_528.svg"),
 ("warning","Uneven road","Неровная дорога","UK_traffic_sign_556.svg"),
 ("warning","Slippery road","Скользкая дорога","UK_traffic_sign_557.svg"),
 ("warning","Side winds","Боковой ветер","UK_traffic_sign_581.svg"),
 ("warning","Low-flying aircraft or sudden aircraft noise","Низколетящие самолёты","UK_traffic_sign_558.svg"),
 ("warning","Low-flying helicopters or sudden helicopter noise","Низколетящие вертолёты","UK_traffic_sign_558.1.svg"),
 ("warning","Falling or fallen rocks","Камнепад","UK_traffic_sign_559_(left).svg"),
 ("warning","Traffic queues likely ahead","Вероятны заторы","UK_traffic_sign_584.svg"),
 ("warning","Slow-moving military vehicles likely","Тихоходная военная техника","UK_traffic_sign_582.svg"),
 ("warning","Slow-moving vehicles","Тихоходный транспорт","UK_traffic_sign_583.svg"),
 ("warning","Ice or snowdrifts","Гололёд или снежные заносы","UK_traffic_sign_554.2.svg"),
 ("warning","Other dangers (with explanatory plate)","Прочие опасности (с поясняющей табличкой)","UK_traffic_sign_562.svg"),
 ("warning","Pedestrian crossing","Пешеходный переход","UK_traffic_sign_544.svg"),
 ("warning","Pedestrians ahead","Пешеходы на дороге","UK_traffic_sign_544.1.svg"),
 ("warning","Frail or disabled pedestrians likely to cross","Пожилые или слабовидящие пешеходы","UK_traffic_sign_544.2.svg"),
 ("warning","School crossing","Школьный переход, дети","Cyprus_warning_road_sign_child.svg"),
 ("warning","Frequent use of road by children","Дорога, часто используемая детьми","frequent_use_of_road_by_childern.png"),
 ("warning","Horse-drawn vehicles likely ahead","Гужевой транспорт","UK_traffic_sign_550.2.svg"),
 ("warning","Accompanied horses or ponies likely ahead","Сопровождаемые лошади или пони","UK_traffic_sign_550.1.svg"),
 ("warning","Wild horses or ponies","Дикие лошади или пони","UK_traffic_sign_550.svg"),
 ("warning","Wild animals","Дикие животные","UK_traffic_sign_551.svg"),
 ("warning","Agricultural vehicles","Сельскохозяйственная техника","UK_traffic_sign_553.1.svg"),
 ("warning","Cattle","Скот","UK_traffic_sign_548.svg"),
 ("warning","Tramway","Трамвайные пути","UK_traffic_sign_772.svg"),
 ("warning","Distance to 'Give Way' line ahead","Расстояние до линии «Уступите дорогу»","Cyprus_warning_road_sign_give_way_ahead.svg"),
 ("warning","Distance to 'STOP' line ahead","Расстояние до линии «Стоп»","Cyprus_warning_road_sign_stop_ahead.svg"),
 ("warning","Electrified overhead cable ahead","Электрифицированный провод над дорогой","UK_traffic_sign_779.svg"),
 ("warning","Road works","Дорожные работы","UK_traffic_sign_7001.svg"),
 ("warning","Loose chippings","Выброс гравия","UK_traffic_sign_7009.svg"),
 ("warning","No barrier level crossing (nearby)","Ж/д переезд без шлагбаума (рядом)","UK_traffic_sign_774.svg"),
 ("warning","Level crossing with barrier or gate","Ж/д переезд со шлагбаумом","UK_traffic_sign_770.svg"),
 ("warning","Level crossing without barrier or gate","Ж/д переезд без шлагбаума","UK_traffic_sign_771.svg"),
 ("warning","Risk of grounding","Риск задевания днищем","UK_traffic_sign_782.svg"),
 ("warning","Road hump","Искусственная неровность","road_hump.png"),
 # ------------------- ADDITIONAL MARKINGS (7) -------------------
 ("additional_markings","Countdown markers to a level crossing","Отсчёт расстояния до ж/д переезда (каждая полоса — 1/3 пути)","Cyprus_warning_road_sign_distance_to_level_crossing.svg"),
 ("additional_markings","Compulsory directions: traffic island or obstacle","Объезд островка или препятствия","Cyprus_road_sign_obstacle.svg"),
 ("additional_markings","Compulsory directions: obstacle (left)","Объезд препятствия слева","Cyprus_warning_road_sign_obstacle_left.svg"),
 ("additional_markings","Compulsory directions: obstacle (right)","Объезд препятствия справа","Cyprus_warning_road_sign_obstacle_right.svg"),
 ("additional_markings","Compulsory direction to the left","Обязательное направление налево","temporary_sharp_deviation.png"),
 ("additional_markings","Compulsory direction to the right","Обязательное направление направо","compulsory_direction_to_the_right.png"),
 ("additional_markings","Compulsory direction to the left or right","Обязательное направление налево или направо","compulsory_direction_to_the_left_or_right.png"),
 # ------------------------ PROHIBITORY (35) ------------------------
 ("prohibitory","No hand vehicles","Движение ручных тележек запрещено","Cyprus_road_sign_no_hand_vehicles.svg"),
 ("prohibitory","No motorcycles","Движение мотоциклов запрещено","Cyprus_road_sign_no_motorcycles.svg"),
 ("prohibitory","No mopeds","Движение мопедов запрещено","Cyprus_road_sign_no_mopeds.svg"),
 ("prohibitory","No pedestrians","Движение пешеходов запрещено","no-crossing-for-pedestrian.jpg"),
 ("prohibitory","No motor vehicles","Движение механических ТС запрещено","Cyprus_road_sign_no_motor_vehicles.svg"),
 ("prohibitory","No agricultural vehicles","Движение сельхозтехники запрещено","Cyprus_road_sign_no_agricle_vehicles.svg"),
 ("prohibitory","No animal-drawn vehicles","Движение гужевого транспорта запрещено","Cyprus_road_sign_no_animal_vehicles.svg"),
 ("prohibitory","Stop. Toll post","Стоп. Пункт оплаты","Cyprus_road_sign_toll_post.svg"),
 ("prohibitory","No horn","Звуковой сигнал запрещён","Cyprus_road_sign_no_horn.svg"),
 ("prohibitory","Stop. Customs","Стоп. Таможня","Cyprus_road_sign_customs.svg"),
 ("prohibitory","Minimum distance","Минимальная дистанция","Cyprus_road_sign_minimum_distance.svg"),
 ("prohibitory","No motor vehicles (car and motorcycle)","Движение авто и мотоциклов запрещено","UK_traffic_sign_619.svg"),
 ("prohibitory","Priority over vehicles from the opposite direction","Преимущество перед встречным движением","UK_traffic_sign_811.svg"),
 ("prohibitory","No vehicles (road closed)","Движение запрещено в обоих направлениях","UK_traffic_sign_617.svg"),
 ("prohibitory","No vehicles over width shown","Ограничение ширины","Cyprus_road_sign_maximum_large.svg"),
 ("prohibitory","No vehicles over height shown","Ограничение высоты","Cyprus_road_sign_maximum_height.svg"),
 ("prohibitory","No heavy vehicles exceeding weight on the sign","Движение грузовиков тяжелее указанного запрещено","UK_traffic_sign_622.1A.svg"),
 ("prohibitory","No heavy vehicles","Движение грузового транспорта запрещено","Cyprus_road_sign_no_heavy_vehicles.svg"),
 ("prohibitory","No towed caravans","Движение с прицепами-дачами запрещено","UK_traffic_sign_622.7.svg"),
 ("prohibitory","No entry","Въезд запрещён","UK_traffic_sign_616.svg"),
 ("prohibitory","No right turn","Поворот направо запрещён","UK_traffic_sign_612.svg"),
 ("prohibitory","No left turn","Поворот налево запрещён","UK_traffic_sign_613.svg"),
 ("prohibitory","Maximum speed limit","Ограничение максимальной скорости","Cyprus_road_sign_maximum_speed.svg"),
 ("prohibitory","End of maximum speed limit","Конец ограничения максимальной скорости","Cyprus_road_sign_end_maximum_speed.svg"),
 ("prohibitory","Priority of vehicles from the opposite direction","Преимущество встречного движения","UK_traffic_sign_615.svg"),
 ("prohibitory","No overtaking","Обгон запрещён","UK_traffic_sign_632.svg"),
 ("prohibitory","End of no overtaking","Конец зоны запрета обгона","Cyprus_road_sign_end_no_overpass.svg"),
 ("prohibitory","No overtaking by heavy vehicles","Обгон грузовым транспортом запрещён","Cyprus_road_sign_no_overpass_heavy_vehicles.svg"),
 ("prohibitory","Maximum single axle weight","Ограничение нагрузки на ось","Cyprus_road_sign_maximum_single_weight.svg"),
 ("prohibitory","End of all local bans on moving vehicles","Конец всех местных ограничений","UK_traffic_sign_671.svg"),
 ("prohibitory","No vehicles over length shown","Ограничение длины","Cyprus_road_sign_maximum_lenght.svg"),
 ("prohibitory","No carrying materials that pollute water","Перевозка веществ, загрязняющих воду, запрещена","Cyprus_road_sign_no_water_heavy_vehicles.svg"),
 ("prohibitory","No vehicles over weight shown","Ограничение массы","Cyprus_road_sign_maximum_heavy.svg"),
 ("prohibitory","Carrying explosives prohibited","Перевозка взрывчатых веществ запрещена","UK_traffic_sign_622.8.svg"),
 ("prohibitory","No U-turns","Разворот запрещён","UK_traffic_sign_614.svg"),
 # ------------------------ REGULATORY (19) ------------------------
 ("regulatory","Stop. Police roadblock","Стоп. Полицейский пост","Cyprus_road_sign_police.svg"),
 ("regulatory","Stop sign","Стоп, обязательная остановка","Cyprus_road_sign_-_STOP.svg"),
 ("regulatory","Priority road","Главная дорога","Cyprus_road_sign_priority_road.svg"),
 ("regulatory","End of priority road","Конец главной дороги","Cyprus_road_sign_end_priority_road.svg"),
 ("regulatory","Stop, crossroads by children","Стоп: переход, используемый детьми","UK_traffic_sign_605.2.svg"),
 ("regulatory","Manually operated temporary GO sign","Ручной временный знак «Ехать»","UK_traffic_sign_7024.svg"),
 ("regulatory","Manually operated temporary STOP sign","Ручной временный знак «Стоп»","manually_operated_temporary_STOP_signs.png"),
 ("regulatory","Give way","Уступите дорогу","Cyprus_road_sign_give_way.svg"),
 ("regulatory","Box junction sign","Перекрёсток с жёлтой сеткой","Cyprus_road_sign_cross_guided.svg"),
 ("regulatory","Road hump ahead with speed limit","Неровность с ограничением скорости","Cyprus_road_sign_road_bump_50.svg"),
 ("regulatory","Humped crossing","Приподнятый пешеходный переход","Cyprus_road_sign_humped_crossing.svg"),
 ("regulatory","Humped pelican crossing","Приподнятый регулируемый переход","Cyprus_road_sign_humped_pellcan_crossing.svg"),
 ("regulatory","School","Школа","Cyprus_road_sign_school.svg"),
 ("regulatory","Road humps left","Неровности слева","Cyprus_road_sign_road_humps_left.svg"),
 ("regulatory","Road humps right","Неровности справа","Cyprus_road_sign_road_humps_right.svg"),
 ("regulatory","Road humps","Участок с неровностями","Cyprus_road_sign_road_humps.svg"),
 ("regulatory","Living street","Жилая зона","Vienna_Convention_road_sign.svg"),
 ("regulatory","End of living street","Конец жилой зоны","Vienna_Convention_road_sign_end.svg"),
 ("regulatory","Beginning of bus only lane","Начало полосы для автобусов","Beginning-of-bus-only-lane.png"),
 # ------------------------ NO PARKING (6) ------------------------
 ("no_parking","No parking","Стоянка запрещена","UK_traffic_sign_636.svg"),
 ("no_parking","No stopping or parking (clearway)","Остановка и стоянка запрещены","UK_traffic_sign_642.svg"),
 ("no_parking","No parking on odd days of the month","Стоянка запрещена по нечётным числам","Cyprus_road_sign_no_park_impares.svg"),
 ("no_parking","No parking on even days of the month","Стоянка запрещена по чётным числам","Cyprus_road_sign_no_park_pares.svg"),
 ("no_parking","No parking zone","Зона запрета стоянки","Cyprus_road_sign_no_parking_zone.svg"),
 ("no_parking","End of no parking zone","Конец зоны запрета стоянки","Cyprus_road_sign_end_no_parking_zone.svg"),
 # ------------------------ MANDATORY (23) ------------------------
 ("mandatory","Go straight ahead only","Движение только прямо","Cyprus_road_sign_mandatory_go_streight.svg"),
 ("mandatory","Turn left","Поворот налево","UK_traffic_sign_606_(left).svg"),
 ("mandatory","Turn right","Поворот направо","UK_traffic_sign_606_(right).svg"),
 ("mandatory","Turn left ahead","Движение налево (впереди)","UK_traffic_sign_609_(left).svg"),
 ("mandatory","Turn right ahead","Движение направо (впереди)","UK_traffic_sign_609_(right).svg"),
 ("mandatory","Go straight or turn left ahead","Прямо или налево","Cyprus_road_sign_mandatory_go_or_left.svg"),
 ("mandatory","Go straight or turn right ahead","Прямо или направо","Cyprus_road_sign_mandatory_go_or_right.svg"),
 ("mandatory","Turn left or right ahead","Налево или направо","Cyprus_road_sign_mandatory_left_or_right.svg"),
 ("mandatory","Keep left","Держитесь левее","UK_traffic_sign_610_(left).svg"),
 ("mandatory","Keep right","Держитесь правее","UK_traffic_sign_610_(right).svg"),
 ("mandatory","Pass on either side","Объезд с любой стороны","UK_traffic_sign_611.svg"),
 ("mandatory","Roundabout (mandatory)","Круговое движение","UK_traffic_sign_611.1.svg"),
 ("mandatory","One-way traffic","Одностороннее движение","Cyprus_road_sign_one_way_road.svg"),
 ("mandatory","One-way road (lateral)","Одностороннее движение (боковая табличка)","Cyprus_road_sign_one_way_lateral_road.svg"),
 ("mandatory","Minimum speed limit","Минимальная скорость","UK_traffic_sign_672.svg"),
 ("mandatory","End of minimum speed limit","Конец зоны минимальной скорости","UK_traffic_sign_673.svg"),
 ("mandatory","Snow chains mandatory","Цепи противоскольжения обязательны","Cyprus_road_sign_mandatory_chains.svg"),
 ("mandatory","Horse street mandatory","Дорожка для всадников","Cyprus_road_sign_horse_street.svg"),
 ("mandatory","Pedestrian road mandatory","Пешеходная дорожка","Cyprus_road_sign_mandatory_pedestrian_way.svg"),
 ("mandatory","Parking (taxi only)","Стоянка только для такси","parking_taxi_only.png"),
 ("mandatory","Bus only lane","Полоса только для автобусов","Bus-only-lane.png"),
 ("mandatory","End of bus only passageway (with distance)","Конец автобусной полосы (с расстоянием)","End-of-bus-only-passageway-with-distance.png"),
 ("mandatory","Compulsory bus only passageway","Обязательный проезд только для автобусов","Compulsory-bus-only-passageway.png"),
 # ------------------------ INFORMATION (43) ------------------------
 ("info","Direction sign","Указатель направлений","Cyprus_road_sign_next_destinations.svg"),
 ("info","Direction sign (at a road crossing)","Указатель направлений на перекрёстке","Cyprus_road_sign_destinations_road_crossing.svg"),
 ("info","Direction sign (white)","Указатель направлений (белый)","Cyprus_road_sign_destinations_white.svg"),
 ("info","Direction sign (blue)","Указатель направлений (синий)","Cyprus_road_sign_destinations_blue.svg"),
 ("info","Bus stop","Остановка автобуса","Cyprus_road_sign_bus_stop.svg"),
 ("info","Pedestrian crossing","Пешеходный переход","Cyprus_road_sign_pedonal_crossing.svg"),
 ("info","Parking","Парковка","Cyprus_road_sign_parking.svg"),
 ("info","Dead end straight ahead","Тупик прямо","Cyprus_road_sign_cul_de_sac.svg"),
 ("info","Dead end left","Тупик слева","Cyprus_road_sign_cul_de_sac_ahead_left.svg"),
 ("info","Dead end right","Тупик справа","Cyprus_road_sign_cul_de_sac_ahead_right.svg"),
 ("info","Emergency phone","Телефон экстренной связи","Cyprus_road_sign_SOS.svg"),
 ("info","Highway road","Дорога для автомобилей","Cyprus_road_sign_road_for_motorvehicles.svg"),
 ("info","End of highway","Конец дороги для автомобилей","Cyprus_road_sign_end_road_for_motorvehicles.svg"),
 ("info","Open road (only with snow chains)","Дорога открыта (только с цепями)","Cyprus_road_sign_transitability.svg"),
 ("info","Drive on the left","Движение левостороннее (у аэропортов и портов)","Cyprus_road_sign_drive_on_the_left.svg"),
 ("info","Vehicle exit","Выезд транспорта","Cyprus_road_sign_vehicles_exit.svg"),
 ("info","General speed limits","Общие ограничения скорости","Cyprus_road_sign_general_limits.svg"),
 ("info","Direction sign at a roundabout","Указатель на круговой развязке","Cyprus_road_sign_roundabound_destinations.svg"),
 ("info","Confirmation sign","Подтверждающий указатель","Cyprus_road_sign_confirm.svg"),
 ("info","City speed limit sign","Ограничение скорости в населённом пункте","City_speed_limit_sign_in_Polis,_Cyprus.svg"),
 ("info","Tunnel ahead","Впереди тоннель","tunnel-ahead.png"),
 ("info","Suggested speed limit","Рекомендуемая скорость","suggested-speed-limit.png"),
 ("info","First aid","Пункт первой помощи","Traffic_Sign_GR_-_KOK_2009_-_P-32.svg"),
 ("info","Repairs","Техобслуживание","Traffic_Sign_GR_-_KOK_2009_-_P-33.svg"),
 ("info","Telephone","Телефон","Traffic_Sign_GR_-_KOK_2009_-_P-34.svg"),
 ("info","Petrol station","АЗС","Traffic_Sign_GR_-_KOK_2009_-_P-35.svg"),
 ("info","Hotel or motel","Гостиница или мотель","Traffic_Sign_GR_-_KOK_2009_-_P-36.svg"),
 ("info","Restaurant","Ресторан","Traffic_Sign_GR_-_KOK_2009_-_P-37.svg"),
 ("info","Refreshments","Кафе, буфет","Traffic_Sign_GR_-_KOK_2009_-_P-38.svg"),
 ("info","Camping zone","Зона отдыха","Traffic_Sign_GR_-_KOK_2009_-_P-39.svg"),
 ("info","Hiking trail","Пешеходный маршрут","Traffic_Sign_GR_-_KOK_2009_-_P-40.svg"),
 ("info","Camping site","Кемпинг","Traffic_Sign_GR_-_KOK_2009_-_P-41.svg"),
 ("info","Caravan site","Стоянка автодомов","Traffic_Sign_GR_-_KOK_2009_-_P-42.svg"),
 ("info","Camping and caravan site","Кемпинг и стоянка автодомов","Traffic_Sign_GR_-_KOK_2009_-_P-43.svg"),
 ("info","Excursion zone","Экскурсионная зона","Traffic_Sign_GR_-_KOK_2009_-_P-44.svg"),
 ("info","Information","Информация","Traffic_Sign_GR_-_KOK_2009_-_P-45.svg"),
 ("info","Toilet","Туалет","Traffic_Sign_GR_-_KOK_2009_-_P-47.svg"),
 ("info","Airport","Аэропорт","Traffic_Sign_GR_-_KOK_2009_-_P-50.svg"),
 ("info","Helicopter","Вертолётная площадка","Traffic_Sign_GR_-_KOK_2009_-_P-51.svg"),
 ("info","Pedestrian overpass","Надземный пешеходный переход","Traffic_Sign_GR_-_KOK_2009_-_P-61.svg"),
 ("info","Pedestrian underpass","Подземный пешеходный переход","Traffic_Sign_GR_-_KOK_2009_-_P-62.svg"),
 ("info","Pedestrian ramp","Пешеходный пандус","Traffic_Sign_GR_-_KOK_2009_-_P-63.svg"),
 # ------------------------ ADDITIONAL PLATES (10) ------------------------
 ("additional","Allowed only for disabled vehicles","Только для ТС инвалидов","Vienna_Convention_road_sign_H7-V1-1.svg"),
 ("additional","No stop and parking, perpendicular to the street","Запрет остановки и стоянки (поперёк улицы)","Vienna_Convention_road_sign_H4a-V1-1.svg"),
 ("additional","Repetition: no stop and parking, perpendicular","Повтор запрета остановки и стоянки (поперёк)","Vienna_Convention_road_sign_H4b-V1-1.svg"),
 ("additional","End of no stop and parking, perpendicular","Конец запрета остановки и стоянки (поперёк)","Vienna_Convention_road_sign_H4c-V1-1.svg"),
 ("additional","Distance from the sign to the signed area","Расстояние до начала зоны действия","Vienna_Convention_road_sign_H1-V1-1.svg"),
 ("additional","Length of the hazardous or restricted section","Протяжённость зоны действия","Vienna_Convention_road_sign_H2-V1-1.svg"),
 ("additional","No stop and parking from sign position, parallel","Запрет остановки и стоянки от знака (вдоль улицы)","Vienna_Convention_road_sign_H3a-V1-1.svg"),
 ("additional","Reminder: no stop and parking, parallel","Повтор запрета остановки и стоянки (вдоль улицы)","Vienna_Convention_road_sign_H3b-V1-1.svg"),
 ("additional","Icy road","Гололёд","Vienna_Convention_road_sign_H9-V1-1.svg"),
 ("additional","Direction of priority road","Направление главной дороги","Vienna_Convention_road_sign_H8b-V1-1.svg"),
 # ------------------------ OTHER OFFICIAL (11) ------------------------
 ("other","Highway","Автомагистраль","Highway_begin_in_Cyprus.png"),
 ("other","End of highway","Конец автомагистрали","Highway_end_in_Cyprus.png"),
 ("other","Highway exit warning","Предупреждение о съезде с автомагистрали","Informational_sign_on_a_motorway_in_Cyprus.svg"),
 ("other","Motorway exit","Съезд с автомагистрали","Motorway_exit_sign_in_Cyprus.png"),
 ("other","Cycle lane","Велосипедная полоса","UK_traffic_sign_955.svg"),
 ("other","Cycle path separated from pedestrian path","Велодорожка, отделённая от пешеходной","UK_traffic_sign_957.svg"),
 ("other","Road shared by cyclists and pedestrians","Совмещённая вело-пешеходная дорожка","UK_traffic_sign_956.svg"),
 ("other","Road shared by bicycles and buses","Полоса для велосипедов и автобусов","UK_traffic_sign_953.svg"),
 ("other","No bicycles allowed","Движение велосипедов запрещено","UK_traffic_sign_951.svg"),
 ("other","Road with special measures for cyclists","Дорога с мерами для велосипедистов","UK_traffic_sign_950.svg"),
 ("other","Speed camera","Камера контроля скорости","UK_traffic_sign_879.svg"),
 # ------------------------ NORTHERN CYPRUS (2) ------------------------
 ("north","Roundabout to population centres and occupied areas","Круговая развязка к населённым пунктам и оккупированным районам","Roundabout_road_sign_in_Cyprus1.svg"),
 ("north","Stop — Turkish occupied area (green line)","Стоп — оккупированная территория (зелёная линия)","Warning_sign_in_Cyprus.png"),
 # ------------------------ WARDEN (6) ------------------------
 ("warden","Stop for traffic from the front","Стоп для транспорта спереди","Stop-for-traffic-approaching-from-the-front.jpg"),
 ("warden","Stop for traffic from both front and behind","Стоп спереди и сзади","Stop-for-traffic-approaching-from-both-front-and-behind.jpg"),
 ("warden","Stop for traffic from behind","Стоп для транспорта сзади","Stop-for-traffic-approaching-from-behind.jpg"),
 ("warden","Proceed: traffic from the front","Проезд транспорту спереди","Proceed-to-traffic-approaching-from-the-front.jpg"),
 ("warden","Proceed: traffic from the side","Проезд транспорту сбоку","Proceed-to-traffic-approaching-from-the-side.jpg"),
 ("warden","Proceed: traffic from behind","Проезд транспорту сзади","Proceed-to-traffic-approaching-from-the-behind.jpg"),
 # ------------------------ ROAD MARKINGS (12) ------------------------
 ("marking","Single continuous line","Одинарная сплошная: обгон запрещён, разделяет встречные потоки","No-parking-or-overtaking.jpg"),
 ("marking","Double continuous lines","Двойная сплошная: обгон запрещён с обеих сторон","No-parking-or-overtaking-1.jpg"),
 ("marking","Single line: solid left, overtaking allowed from right","Комбинированная: сплошная слева, обгон справа разрешён","Overtaking-allowed-from-right.jpg"),
 ("marking","Lane dividers: overtaking is allowed","Прерывистая: обгон разрешён","Overtaking-is-allowed.jpg"),
 ("marking","Zigzag lines: no parking, waiting or overtaking","Зигзаг: стоянка, ожидание и обгон запрещены","No-parking-or-waiting-or-overtaking.jpg"),
 ("marking","White side line: edge of carriageway, no parking","Белая краевая линия: край проезжей части, стоянка запрещена","Depicts-the-side-of-the-carriageway-–-No-parking.png"),
 ("marking","Broken side line: entrances or exits on the left","Прерывистая краевая: въезды и выезды слева","broken-side-line.png"),
 ("marking","Yellow side line: no parking beyond the line","Жёлтая краевая: не парковаться и не выезжать за линию","yellow-side-line.png"),
 ("marking","Double continuous yellow line: no stop, no parking","Двойная жёлтая: остановка и стоянка запрещены","double-continuous-yellow.png"),
 ("marking","Give way T-junction line","Линия «уступи дорогу» на Т-образном перекрёстке","Give-way-to-traffic-on-main-road.jpg"),
 ("marking","Stop T-junction line","Стоп-линия на Т-образном перекрёстке","Stop-and-give-way.jpg"),
 ("marking","Directions on roundabout","Разметка направлений на круговой развязке","Directions-on-roundabout.jpg"),
 # ------------------------ ROUNDABOUTS (2) ------------------------
 ("roundabout","Roundabout: 2 lanes directions","Круговая развязка: выбор из 2 полос","Default-roundabout-lane.jpg"),
 ("roundabout","Roundabout: 3 lanes directions","Круговая развязка: выбор из 3 полос","Default-roundabout-lane-1.jpg"),
]

def slug(fname):
    base = unquote(os.path.splitext(fname)[0])
    s = re.sub(r"[^A-Za-z0-9]+", "_", base).strip("_").lower()
    return s

def main():
    os.makedirs(OUT, exist_ok=True)
    seen, cards = set(), []
    for cat, en, ru, fname in S:
        sid = slug(fname)
        if sid in seen:
            sid = f"{cat}_{sid}"
        seen.add(sid)
        ext = os.path.splitext(fname)[1].lower()
        cards.append({
            "id": sid,
            "category": cat,
            "name_en": en,
            "name_ru": ru,
            "image_url": BASE + fname,
            "image": f"assets/img/{sid}{ext}",
        })
    data = {"source": "https://driving.cy/en/signs", "categories": CATEGORIES, "cards": cards}
    with open(os.path.join(OUT, "signs_full.json"), "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    from collections import Counter
    print(Counter(c["category"] for c in cards))
    print("total:", len(cards))

if __name__ == "__main__":
    main()
